In [1]:
# import load_iris function from datasets module
from sklearn.datasets import load_iris

In [2]:
# save "bunch" object containing iris dataset and its attributes
iris = load_iris()
type(iris)

sklearn.utils.Bunch

In [3]:
# Note one of the attributes is called "data". Print the iris data. 
print (iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [5]:
# print the names of the four fratures
print (iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [4]:
# print integers representing the species of each observation
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [5]:
# print the encoding scheme for species: 0 = setosa, 1 = versicolor, 2 = virginica
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [6]:
# check the type of features and response
type(iris.data)
type(iris.target)

numpy.ndarray

In [7]:
# check the shape of the features (1st dim = no. of observations, 2nd dim = no. of features)
print(iris.data.shape)

(150, 4)


In [8]:
# check the shape of the response (single dimension matching the number of observations)
print(iris.target.shape)

(150,)


In [9]:
# store feature matrix in "X". X is capital because it represents a matrix.
X = iris.data

# store response matrix in "y". y is common because it represents a vector.
y = iris.target

In [10]:
print(X.shape)
print(y.shape)

(150, 4)
(150,)


## Machine Learning ##

**Step 1:** Import the class you plan to use

In [11]:
from sklearn.neighbors import KNeighborsClassifier

**Step 2:** "Instantiate" the "estimator"

- "Estimator" is scikit-learn's term for model

- "Instantiate" means "make an instance of"

In [12]:
# We are creating an instance of the KNeighborsClassifier class and calling it knn. 
# i.e. We now have an object called knn that knows how to do KNN classification
knn = KNeighborsClassifier(n_neighbors=1)

Important notes about the instantiator
- Name of the object doesn't matter
- Can specify tuning parameters (aka "hyperparameters") during this step. See n_neighbors=1
- All parameters not specified are set to their defaults. We can see the values by printing out the estimator object

In [13]:
print(knn)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')


**Step 3:** Fit thr model with data (aka "model training")

- Model is learning the relationship between X (features) and y (response)
- Occurs in-place

In [14]:
knn.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

**Step 4:** Predict the response for a new observation
Input the measurements for an unknown iris and ask the fitted mdel to 
predict the iris species based on what it learned in the previous step.

- New observations are called "out-of-sample" data
- Uses the information it learned during the model training process

The "predict" method is used on the knn object and is passed the features of the unknown iris in the form of 
a python list. It's expecting a NumPy array, but it can still work with a list as NumPy automatically
converts it to an array of the appropriate shape.

In [15]:
knn.predict([[3, 5, 4, 2]])

array([2])



- returns a NumPy array
NB scikit-learn doesn't know what this 2 means. We need to remember that 2 is the coding for virginica.

- Can predict multiple observations at once

In [16]:
x_new = [[3, 5, 4, 2], [5, 4, 3, 2]]
knn.predict(x_new)

array([2, 1])

## Using a different value for K ##

In [17]:
# instantialte the model using K = 5
knn = KNeighborsClassifier(n_neighbors=5)

# fit the model with data
knn.fit(X, y)

# predict the response for the new observation
knn.predict(x_new)

array([1, 1])

## Using a different classification model ##

In [18]:
# import the class
from sklearn.linear_model import LogisticRegression

# initiate the model (using the default parameter)
logreg = LogisticRegression()

# fit the model with data
logreg.fit(X, y)

#predict the response for the new observation
logreg.predict(x_new)

c:\users\amritha ramharack\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
c:\users\amritha ramharack\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


array([2, 0])